apiVersion: v1
kind: ConfigMap
metadata:
  name: bank-config
data:
  DB_HOST: "YOUR_DATABASE_HOST_HERE"
  DB_PORT: "3306"
  DB_NAME: "production_db"
  REACT_APP_API_URL: https://bankapi.bcloudsec.space
